@url = http://localhost:8080
@id = 7f0e1e0c-382c-494f-a89c-b7e635da2652

###
GET {{url}}/api/skill

###
GET {{url}}/api/skill/{{id}}

###
POST {{url}}/api/skill
content-type: application/json

{
    "name": "Programming in C#",
    "yearsOfExperience": 17,
    "level": 75
}

###
GET {{url}}/hc/live

###
GET {{url}}/hc/ready