apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-deployment
spec:
  selector:
    matchLabels:
      app: skill
  template:
    metadata:
      labels:
        app: skill
    spec:
      containers:
      - name: skill
        image: hrshojaie/skill:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbOptions__Host
            value: mongodb-service
          - name: MongoDbOptions__Password
            valueFrom:
              secretKeyRef:
                name: skill-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /hc/live
            port: 80
        readinessProbe:
          httpGet:
            path: /hc/ready
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: skill-service
spec:
  type: LoadBalancer
  selector:
    app: skill
  ports:
  - port: 80
    targetPort: 80